# Generated by Django 4.2.11 on 2026-06-06 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('total_products', models.IntegerField(default=0)),
                ('products_with_ingredients', models.IntegerField(default=0)),
                ('analysis_file', models.FileField(blank=True, null=True, upload_to='analyses/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Brand Portfolios',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('selected_portfolios', models.ManyToManyField(blank=True, to='api.brandportfolio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dermacare_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('benefits', models.TextField(blank=True)),
                ('how_to_use', models.TextField(blank=True)),
                ('pdf_ingredients', models.TextField(blank=True, help_text='Ingredients found in PDF')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.brandportfolio')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('portfolio', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients_list', models.TextField(help_text='Comma-separated INCI ingredients')),
                ('source', models.CharField(choices=[('pdf', 'PDF Document'), ('upc_inci', 'UPC ItemDB + INCIApi'), ('gemini', 'Gemini Fallback')], default='pdf', max_length=10)),
                ('barcode', models.CharField(blank=True, help_text='UPC/EAN barcode', max_length=20)),
                ('quality_score', models.IntegerField(blank=True, help_text='INCIApi quality score', null=True)),
                ('found_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='api.product')),
            ],
            options={
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.brandportfolio')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
